### PR TITLE
UPDATE: [elessar.zsh-theme] - update prompt, based on rubbyrussel theme

### PR DESCRIPTION
**Pull request by askariali**
UPDATE: [README.md] - update preview image with new prompt

### CODE REVIEW

**Comment by fjpalacios** [comment]
@askariacc thanks for your PR! If I get it right, your PR changes the color of the prompt and the position of the arrow, right?

**Comment by askariali** [comment]
@fjpalacios yes it is. In some case, the directory route and the typed command by user can making confuse. So I shift the arrow forward to split directory and command

**Comment by fjpalacios** [comment]
@askariacc I agree with this. I actually use multiline mode, so I'm used to seeing the arrow right in front of the command I type. But there may be people who prefer the way it looks now. How about adding a conditional, as it's done with the multiline mode, so each person can configure it to their own preference? And with the color change of the route I would do the same, for those who prefer to keep the Gitster theme style. Thank you again for your contribution!

**Comment by askariali** [comment]
@fjpalacios yea, it's a good point
so I close this PR and I'll create some changes
thanks for your attention

**Pull request closed without merging**
